/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BielyAmbulanceWlApp {
        "ambulanceId": string;
        "apiBase": string;
        /**
          * @default ''
         */
        "basePath": string;
    }
    interface BielyAmbulanceWlEditor {
        "ambulanceId": string;
        "apiBase": string;
        "entryId": string;
    }
    interface BielyAmbulanceWlList {
        "ambulanceId": string;
        "apiBase": string;
    }
}
export interface BielyAmbulanceWlEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBielyAmbulanceWlEditorElement;
}
export interface BielyAmbulanceWlListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBielyAmbulanceWlListElement;
}
declare global {
    interface HTMLBielyAmbulanceWlAppElement extends Components.BielyAmbulanceWlApp, HTMLStencilElement {
    }
    var HTMLBielyAmbulanceWlAppElement: {
        prototype: HTMLBielyAmbulanceWlAppElement;
        new (): HTMLBielyAmbulanceWlAppElement;
    };
    interface HTMLBielyAmbulanceWlEditorElementEventMap {
        "editor-closed": string;
    }
    interface HTMLBielyAmbulanceWlEditorElement extends Components.BielyAmbulanceWlEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLBielyAmbulanceWlEditorElementEventMap>(type: K, listener: (this: HTMLBielyAmbulanceWlEditorElement, ev: BielyAmbulanceWlEditorCustomEvent<HTMLBielyAmbulanceWlEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLBielyAmbulanceWlEditorElementEventMap>(type: K, listener: (this: HTMLBielyAmbulanceWlEditorElement, ev: BielyAmbulanceWlEditorCustomEvent<HTMLBielyAmbulanceWlEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLBielyAmbulanceWlEditorElement: {
        prototype: HTMLBielyAmbulanceWlEditorElement;
        new (): HTMLBielyAmbulanceWlEditorElement;
    };
    interface HTMLBielyAmbulanceWlListElementEventMap {
        "entry-clicked": string;
    }
    interface HTMLBielyAmbulanceWlListElement extends Components.BielyAmbulanceWlList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLBielyAmbulanceWlListElementEventMap>(type: K, listener: (this: HTMLBielyAmbulanceWlListElement, ev: BielyAmbulanceWlListCustomEvent<HTMLBielyAmbulanceWlListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLBielyAmbulanceWlListElementEventMap>(type: K, listener: (this: HTMLBielyAmbulanceWlListElement, ev: BielyAmbulanceWlListCustomEvent<HTMLBielyAmbulanceWlListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLBielyAmbulanceWlListElement: {
        prototype: HTMLBielyAmbulanceWlListElement;
        new (): HTMLBielyAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "biely-ambulance-wl-app": HTMLBielyAmbulanceWlAppElement;
        "biely-ambulance-wl-editor": HTMLBielyAmbulanceWlEditorElement;
        "biely-ambulance-wl-list": HTMLBielyAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface BielyAmbulanceWlApp {
        "ambulanceId"?: string;
        "apiBase"?: string;
        /**
          * @default ''
         */
        "basePath"?: string;
    }
    interface BielyAmbulanceWlEditor {
        "ambulanceId"?: string;
        "apiBase"?: string;
        "entryId"?: string;
        "onEditor-closed"?: (event: BielyAmbulanceWlEditorCustomEvent<string>) => void;
    }
    interface BielyAmbulanceWlList {
        "ambulanceId"?: string;
        "apiBase"?: string;
        "onEntry-clicked"?: (event: BielyAmbulanceWlListCustomEvent<string>) => void;
    }

    interface BielyAmbulanceWlAppAttributes {
        "basePath": string;
        "apiBase": string;
        "ambulanceId": string;
    }
    interface BielyAmbulanceWlEditorAttributes {
        "entryId": string;
        "ambulanceId": string;
        "apiBase": string;
    }
    interface BielyAmbulanceWlListAttributes {
        "apiBase": string;
        "ambulanceId": string;
    }

    interface IntrinsicElements {
        "biely-ambulance-wl-app": Omit<BielyAmbulanceWlApp, keyof BielyAmbulanceWlAppAttributes> & { [K in keyof BielyAmbulanceWlApp & keyof BielyAmbulanceWlAppAttributes]?: BielyAmbulanceWlApp[K] } & { [K in keyof BielyAmbulanceWlApp & keyof BielyAmbulanceWlAppAttributes as `attr:${K}`]?: BielyAmbulanceWlAppAttributes[K] } & { [K in keyof BielyAmbulanceWlApp & keyof BielyAmbulanceWlAppAttributes as `prop:${K}`]?: BielyAmbulanceWlApp[K] };
        "biely-ambulance-wl-editor": Omit<BielyAmbulanceWlEditor, keyof BielyAmbulanceWlEditorAttributes> & { [K in keyof BielyAmbulanceWlEditor & keyof BielyAmbulanceWlEditorAttributes]?: BielyAmbulanceWlEditor[K] } & { [K in keyof BielyAmbulanceWlEditor & keyof BielyAmbulanceWlEditorAttributes as `attr:${K}`]?: BielyAmbulanceWlEditorAttributes[K] } & { [K in keyof BielyAmbulanceWlEditor & keyof BielyAmbulanceWlEditorAttributes as `prop:${K}`]?: BielyAmbulanceWlEditor[K] };
        "biely-ambulance-wl-list": Omit<BielyAmbulanceWlList, keyof BielyAmbulanceWlListAttributes> & { [K in keyof BielyAmbulanceWlList & keyof BielyAmbulanceWlListAttributes]?: BielyAmbulanceWlList[K] } & { [K in keyof BielyAmbulanceWlList & keyof BielyAmbulanceWlListAttributes as `attr:${K}`]?: BielyAmbulanceWlListAttributes[K] } & { [K in keyof BielyAmbulanceWlList & keyof BielyAmbulanceWlListAttributes as `prop:${K}`]?: BielyAmbulanceWlList[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "biely-ambulance-wl-app": LocalJSX.IntrinsicElements["biely-ambulance-wl-app"] & JSXBase.HTMLAttributes<HTMLBielyAmbulanceWlAppElement>;
            "biely-ambulance-wl-editor": LocalJSX.IntrinsicElements["biely-ambulance-wl-editor"] & JSXBase.HTMLAttributes<HTMLBielyAmbulanceWlEditorElement>;
            "biely-ambulance-wl-list": LocalJSX.IntrinsicElements["biely-ambulance-wl-list"] & JSXBase.HTMLAttributes<HTMLBielyAmbulanceWlListElement>;
        }
    }
}
