/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BbAmbulanceWlList {
    }
}
declare global {
    interface HTMLBbAmbulanceWlListElement extends Components.BbAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLBbAmbulanceWlListElement: {
        prototype: HTMLBbAmbulanceWlListElement;
        new (): HTMLBbAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "bb-ambulance-wl-list": HTMLBbAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface BbAmbulanceWlList {
    }
    interface IntrinsicElements {
        "bb-ambulance-wl-list": BbAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bb-ambulance-wl-list": LocalJSX.IntrinsicElements["bb-ambulance-wl-list"] & JSXBase.HTMLAttributes<HTMLBbAmbulanceWlListElement>;
        }
    }
}
